version: '3.3'

volumes:
  sense-docs:

services:

  qix:
    container_name: qix
    image: "qlikcore/engine:${QIX_ENGINE_VER:-latest}"
    command: [
       "-S", "DocumentDirectory=/docs",
       "-S", "AcceptEULA=yes"
     ]
    volumes:
      - sense-docs:/docs
    ports:
      - "9076:9076"
    expose:
      - 9076

  sense-docs:
    image: stefanwalther/sense-docs
    volumes:
      - sense-docs:/opt/sense-docs/docs
    tty: true

  qix-graphql:
    container_name: qix-graphql
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3004:3004"
    environment:
      - QIX_HOST=qix
      - QIX_PORT=9076
      - HOST=qix-graphql
      - PORT=3004
    restart: always
    command: ["npm", "run", "start:watch"]
    volumes:
      - ./src/:/opt/qix-graphql/src
