version: '3.3'

volumes:
  sense-docs:

services:

  qix:
    container_name: qix
    image: qlik/engine:latest
    command: [
      "-S", "DocumentDirectory=/docs",
      "-S", "AcceptEULA=yes"
    ]
    volumes:
      - sense-docs:/docs
    ports:
      - "9076:9076"
    expose:
      - 9076

  sense-docs:
    image: stefanwalther/sense-docs
    volumes:
      - sense-docs:/opt/sense-docs/docs
    tty: true

  qix-graphql:
    container_name: qix-graphql
    build:
      context: .
    ports:
      - "3004:3004"
    environment:
      - QIX_HOST=qix
    restart: always
    command: ["npm", "run", "start"]
    volumes:
      - ./src/:/opt/qix-graphql/src
